<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0-windows10.0.17763.0</TargetFramework>
        <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
        <!-- Build on macOS/Linux -->
        <EnableWindowsTargeting>true</EnableWindowsTargeting>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.Toolkit.Uwp.Notifications"/>
        <!--Nuget use 4.7.0 by default, this is bad! use by Microsoft.Toolkit.Uwp.Notifications / System.Data.SQLite 1.x (by EF6)-->
        <PackageReference Include="System.Drawing.Common" VersionOverride="10.0.2"/>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\VRCX.Core\VRCX.Core.csproj"/>
    </ItemGroup>

</Project>
