<Project>
    <!-- https://learn.microsoft.com/en-us/nuget/consume-packages/central-package-management -->
    <PropertyGroup>
        <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
    </PropertyGroup>
    <ItemGroup>
        <PackageVersion Include="Microsoft.Extensions.DependencyInjection" Version="10.0.2"/>
        <PackageVersion Include="Polly.Core" Version="8.6.5"/>

        <PackageVersion Include="System.Data.SQLite" Version="2.0.2"/>
        <PackageVersion Include="SourceGear.sqlite3" Version="3.50.4.5"/>
        <PackageVersion Include="System.Management" Version="10.0.2"/>
        <PackageVersion Include="SixLabors.ImageSharp" Version="3.1.12"/>
        <PackageVersion Include="SixLabors.ImageSharp.Drawing" Version="2.1.7"/>

        <PackageVersion Include="Microsoft.Toolkit.Uwp.Notifications" Version="7.1.3"/>

        <!--Serilog Logging-->
        <PackageVersion Include="Serilog" Version="4.3.0"/>
        <PackageVersion Include="Serilog.Formatting.Compact" Version="3.0.0"/>
        <PackageVersion Include="Serilog.Sinks.Console" Version="6.1.1"/>
        <PackageVersion Include="Serilog.Sinks.Debug" Version="3.0.0"/>
        <PackageVersion Include="Serilog.Sinks.File" Version="7.0.0"/>
    </ItemGroup>
</Project>