<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <IsAotCompatible>true</IsAotCompatible>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="System.Data.SQLite"/>
        <PackageReference Include="SourceGear.sqlite3"/>
        <PackageReference Include="SixLabors.ImageSharp"/>
        <PackageReference Include="SixLabors.ImageSharp.Drawing"/>
        <PackageReference Include="Microsoft.Extensions.DependencyInjection"/>

        <!--Serilog Logging-->
        <PackageReference Include="Serilog"/>
        <PackageReference Include="Serilog.Formatting.Compact"/>
        <PackageReference Include="Serilog.Sinks.Console"/>
        <PackageReference Include="Serilog.Sinks.Debug"/>
        <PackageReference Include="Serilog.Sinks.File"/>
    </ItemGroup>

    <ItemGroup>
        <Reference Include="librsync.net">
            <HintPath>..\..\..\Dotnet\libs\librsync.net.dll</HintPath>
        </Reference>
    </ItemGroup>

    <ItemGroup>
        <None Include="..\..\..\Version">
            <CopyToOutputDirectory>Always</CopyToOutputDirectory>
        </None>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\OverlayClient\VRCX.Core.OverlayClient.XsOverlay\VRCX.Core.OverlayClient.XsOverlay.csproj"/>
        <ProjectReference Include="..\OverlayClient\VRCX.Core.OverlayClient.OvrToolkit\VRCX.Core.OverlayClient.OvrToolkit.csproj"/>
        <ProjectReference Include="..\VRCX.Core.DiscordRpc\VRCX.Core.DiscordRpc.csproj" />
        <ProjectReference Include="..\VRCX.Core.ScreenshotManagement\VRCX.Core.ScreenshotManagement.csproj" />
        <ProjectReference Include="..\VRCX.Core.WebLocalFileAccess\VRCX.Core.WebLocalFileAccess.csproj" />
        <ProjectReference Include="..\VRCX.Core.Shared\VRCX.Core.Shared.csproj" />
    </ItemGroup>

</Project>
